/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_maxzuo_jni_StringUtils */

#ifndef _Included_com_maxzuo_jni_StringUtils
#define _Included_com_maxzuo_jni_StringUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_maxzuo_jni_StringUtils
 * Method:    getRandStr
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_maxzuo_jni_StringUtils_getRandStr
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
